- name: Download Grafana GPG key
  ansible.builtin.get_url:
    url: "https://packages.grafana.com/gpg.key"
    dest: "/tmp/grafana.gpg"

- name: Import GPG key
  ansible.builtin.shell: "rpm --import /tmp/grafana.gpg"

- name: Install grafana
  yum:
    name: https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana-{{ version }}-1.x86_64.rpm
    state: latest

- name: "Grafana configuration file copy"
  template:
    src: "grafana.conf.j2"
    dest: /etc/grafana/grafana.ini
  notify: event_restart_grafana

- name: "Grafana server started"
  service:
    name: grafana-server
    enabled: true
    state: started

- name: "Check if Grafana is accessible."
  uri:
    url: http://127.0.0.1:3000
    method: GET
    status_code: 200